name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Dotnet Publish
      run: dotnet publish ASPNetCore/ASPNetCore.sln -c Release -o deploy
    - name: git-ftp-action
      uses: sebastianpopp/git-ftp-action@2.1.0
      with:
        local: /home/runner/work/dev2/dev2/deploy/
        ftp-server: ${{ secrets.ftp_host }}
        ftp-username: ${{ secrets.ftp_username }}
        ftp-password: ${{ secrets.ftp_password }}
