name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.101
    - name: Dotnet Publish
      run: dotnet publish ASPNetCore/ASPNetCore.sln -c Release -o deploy
    - name: git-ftp push
      uses: vuonghovan/dev2@releases/master
      with:
        url: "${{ secrets.ftp_host }}"
        user: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
